spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisBDev/spring-microservices-hr-management-resilience4j.git
          search-paths: infra/config-server-properties
          clone-on-start: true
          default-label: master
          username: LuisBDev
          password: ${GIT_PASSWORD_TOKEN}
          force-pull: true
