
http-clients:
  internal:
    employee-ms:
      base-url: http://localhost:40070/api/v1/employees
      timeout: 5s
    department-ms:
      base-url: http://localhost:40080/api/v1/departments
      timeout: 5s
